name: PortalsPE
main: luca28pet\PortalsPE\Main
api: 3.0.0
version: 2.0.0
author: luca28pet
description: A portals plugin
permission:
  portalspe:
    default: op
    children:
      portalspe.portal:
        default: false
      portalspe.command:
        default: false
        children:
          portalspe.command.portal:
            default: op
