name: PortalsPE
main: PortalsPE\Main
api: 3.0.0-ALPHA12
version: 1.1
author: luca28pet
description: A portals plugin
commands:
  portal:
    description: Main PortalsPE commmand
    usage: /portal pos1|pos2|create|list
    permission: portal.admin
permission:
  portal.admin:
    description: admin command
    default: op
