---
#Choose how the plugin detects players movement: use "event" to use PlayerMoveEvent or "task" to use a repeating task
#Best choice may be "task"
movement-detection: "task"

#Task time in seconds (only matters when "task" is selected in the previous field)
task-time: 3

#Language for players messages
message-error: "The destination of this portal is in a world that does not exist or is not loaded"
message-no-perm: "You do not have permission to use this portal"
message-tp: "You have entered the portal"
...